--CONSTRAINTS SCHEMA MASTER
--Tabla Clientes Banco
ALTER TABLE C##MASTER.CLIENTES_BANCO ADD CONSTRAINT CLB_PK PRIMARY KEY (id_cliente);
ALTER TABLE C##MASTER.CLIENTES_BANCO ADD CONSTRAINT CLB_UK UNIQUE (rut);

--Tabla Tipo Cuentas
ALTER TABLE C##MASTER.TIPO_CUENTAS ADD CONSTRAINT TC_PK PRIMARY KEY (id_tipo_cuenta);

--Tabla Tipo Movimientos
ALTER TABLE C##MASTER.TIPO_MOVIMIENTOS ADD CONSTRAINT TM_PK PRIMARY KEY (id_tipo_movimiento);


-- CONTRAINTS SCHEMA FINANZAS
--Tabla Cuentas
ALTER TABLE C##FINANZAS.CUENTAS ADD CONSTRAINT FC_PK PRIMARY KEY (id_cuenta);
ALTER TABLE C##FINANZAS.CUENTAS ADD CONSTRAINT FC_CLB_FK FOREIGN KEY (id_cliente) REFERENCES C##MASTER.CLIENTES_BANCO(id_cliente);
ALTER TABLE C##FINANZAS.CUENTAS ADD CONSTRAINT FC_TC_FK FOREIGN KEY (id_tipo_cuenta) REFERENCES C##MASTER.TIPO_CUENTAS(id_tipo_cuenta);
ALTER TABLE C##FINANZAS.CUENTAS ADD CONSTRAINT FC_ESTD_CHK CHECK (estado in ('A','I'));
ALTER TABLE C##FINANZAS.CUENTAS ADD CONSTRAINT FC_SDCT_CHK CHECK (saldo_contable>=0);
ALTER TABLE C##FINANZAS.CUENTAS ADD CONSTRAINT FC_SDSG_CHK CHECK (saldo_sobregiro>=0);

--Tabla Tarjetas
ALTER TABLE C##FINANZAS.TARJETAS ADD CONSTRAINT FT_PK PRIMARY KEY (id_tarjeta);
ALTER TABLE C##FINANZAS.TARJETAS ADD CONSTRAINT FT_FC_FK FOREIGN KEY (id_cuenta) REFERENCES C##FINANZAS.CUENTAS(id_cuenta);
ALTER TABLE C##FINANZAS.TARJETAS ADD CONSTRAINT FT_ESTD_CHK CHECK (estado in ('A','I'));

--Tabla Movimientos
ALTER TABLE C##FINANZAS.MOVIMIENTOS ADD CONSTRAINT FM_PK PRIMARY KEY (id_movimiento);
ALTER TABLE C##FINANZAS.MOVIMIENTOS ADD CONSTRAINT FM_FC_FK FOREIGN KEY (id_cuenta_origen) REFERENCES C##FINANZAS.CUENTAS(id_cuenta);
ALTER TABLE C##FINANZAS.MOVIMIENTOS ADD CONSTRAINT FM_TM_FK FOREIGN KEY (id_tipo_movimiento) REFERENCES C##MASTER.TIPO_MOVIMIENTOS(id_tipo_movimiento);
ALTER TABLE C##FINANZAS.MOVIMIENTOS ADD CONSTRAINT FM_CAB_CHK CHECK (ind_cargo_abono in ('C','A'));
ALTER TABLE C##FINANZAS.MOVIMIENTOS ADD CONSTRAINT FM_MNT_CHK CHECK (monto>=0);


