--Permisos de sistemas
GRANT REFERENCES ON C##MASTER.CLIENTES_BANCO TO C##FINANZAS;
GRANT REFERENCES ON C##MASTER.TIPO_CUENTAS TO C##FINANZAS;
GRANT REFERENCES ON C##MASTER.TIPO_MOVIMIENTOS TO C##FINANZAS;

--Permisos de objetos
GRANT SELECT, INSERT ON C##FINANZAS.CUENTAS TO C##MASTER;
GRANT SELECT ON C##FINANZAS.SQC_ID_CUENTA TO C##MASTER;
GRANT SELECT, INSERT ON C##FINANZAS.TARJETAS TO C##MASTER;
GRANT SELECT ON C##FINANZAS.SQC_ID_MOV TO C##MASTER;

GRANT SELECT, INSERT ON C##FINANZAS.MOVIMIENTOS TO C##MASTER;
GRANT SELECT, INSERT, UPDATE ON C##FINANZAS.CUENTAS TO C##MASTER;
GRANT SELECT ON C##FINANZAS.SQC_ID_CUENTA  TO C##MASTER;
GRANT SELECT, INSERT ON C##FINANZAS.TARJETAS TO C##MASTER;
