--Creación de Sinonimos para facilitar codificacion de procedures y packages
CREATE PUBLIC SYNONYM CLIENTES_BANCO FOR C##MASTER.CLIENTES_BANCO;
CREATE PUBLIC SYNONYM TIPO_CUENTAS FOR C##MASTER.TIPO_CUENTAS;
CREATE PUBLIC SYNONYM TIPO_MOVIMIENTOS FOR C##MASTER.TIPO_MOVIMIENTOS;

CREATE PUBLIC SYNONYM CUENTAS FOR C##FINANZAS.CUENTAS;
CREATE PUBLIC SYNONYM TARJETAS FOR C##FINANZAS.TARJETAS;
CREATE PUBLIC SYNONYM MOVIMIENTOS FOR C##FINANZAS.MOVIMIENTOS;

