-- Creacion de usuarios
CREATE USER C##MASTER IDENTIFIED BY MASTER;
CREATE USER C##FINANZAS IDENTIFIED BY FINANZAS;

--Asignacion de Tablespace
GRANT UNLIMITED TABLESPACE TO C##MASTER;
GRANT UNLIMITED TABLESPACE TO C##FINANZAS;

--Asignar permisos de conexion
GRANT CONNECT TO C##MASTER;
GRANT CONNECT TO C##FINANZAS;
